In [22]:
import pickle

import numpy as np
import pandas as pd

In [4]:
with open("dataset.pkl", "rb") as f:
    DATA = pickle.load(f)
    pheno = DATA["pheno"]
    X_gpa = pd.DataFrame(DATA["X_gpa"])
    X_snps = pd.DataFrame(DATA["X_snps"])
    X_genexp = pd.DataFrame(DATA["X_genexp"])

# Réponse

In [43]:
Y = pd.DataFrame(pheno.iloc[:, 1:])
Y = Y.set_index(pheno["strain_ids"])

In [59]:
Y.isna().sum()

Tobramycin        8
Ceftazidim       80
Ciprofloxacin    56
Meropenem        60
Colistin          0
dtype: int64

In [45]:
Y_desc = Y.astype("object").describe()
Y_desc

Tobramycin  Ceftazidim  Ciprofloxacin  Meropenem  Colistin
count        406.0       334.0          358.0      354.0       414
unique         2.0         2.0            2.0        2.0         2
top            0.0         0.0            1.0        1.0         0
freq         276.0       169.0          199.0      244.0       329

In [70]:
Y_bincount = Y.apply(lambda x: np.bincount(x.dropna()), axis=0)
Y_bincount

Tobramycin  Ceftazidim  Ciprofloxacin  Meropenem  Colistin
0         276         169            159        110       329
1         130         165            199        244        85

# Régresseurs

## X_gpa

In [30]:
X_gpa.isna().sum().sum()

0

In [46]:
X_gpa_desc = X_gpa.astype("object").describe()
X_gpa_desc

0      1      2      3      4      5      6      7      8      9      \
count   414.0  414.0  414.0  414.0  414.0  414.0  414.0  414.0  414.0  414.0   
unique    2.0    2.0    2.0    2.0    2.0    2.0    2.0    2.0    2.0    1.0   
top       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0   
freq    384.0  402.0  403.0  413.0  399.0  389.0  413.0  413.0  413.0  414.0   

        ...  15995  15996  15997  15998  15999  16000  16001  16002  16003  \
count   ...  414.0  414.0  414.0  414.0  414.0  414.0  414.0  414.0  414.0   
unique  ...    2.0    2.0    2.0    2.0    2.0    2.0    2.0    2.0    2.0   
top     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
freq    ...  382.0  393.0  368.0  375.0  365.0  365.0  385.0  365.0  370.0   

        16004  
count   414.0  
unique    2.0  
top       0.0  
freq    364.0  

[4 rows x 16005 columns]

In [76]:
np.bincount(X_gpa_desc.transpose()["unique"])

array([    0,    26, 15979])

In [77]:
X_gpa_bincount = np.bincount(X_gpa_desc.transpose()["top"])
X_gpa_bincount

array([12424,  3581])

## X_snps

In [31]:
X_snps.isna().sum().sum()

0

In [48]:
X_snps_desc = X_snps.astype("object").describe()
X_snps_desc

0      1      2      3      4      5      6      7      8      9      \
count   414.0  414.0  414.0  414.0  414.0  414.0  414.0  414.0  414.0  414.0   
unique    2.0    2.0    2.0    2.0    2.0    2.0    2.0    2.0    2.0    2.0   
top       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
freq    413.0  413.0  412.0  413.0  411.0  413.0  413.0  411.0  413.0  413.0   

        ...  72226  72227  72228  72229  72230  72231  72232  72233  72234  \
count   ...  414.0  414.0  414.0  414.0  414.0  414.0  414.0  414.0  414.0   
unique  ...    2.0    2.0    2.0    2.0    2.0    2.0    2.0    2.0    2.0   
top     ...    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0   
freq    ...  412.0  409.0  408.0  409.0  412.0  411.0  410.0  412.0  412.0   

        72235  
count   414.0  
unique    2.0  
top       1.0  
freq    413.0  

[4 rows x 72236 columns]

In [52]:
np.bincount(X_snps_desc.transpose()["unique"])

array([    0,     0, 72236])

In [78]:
X_snps_bincount = np.bincount(X_snps_desc.transpose()["top"])
X_snps_bincount

array([64018,  8218])

## X_genexp

In [32]:
X_genexp.isna().sum().sum()

0

In [25]:
X_genexp_desc = X_genexp.describe(percentiles=[])
X_genexp_desc

0           1           2           3           4           5     \
count  414.000000  414.000000  414.000000  414.000000  414.000000  414.000000   
mean    -0.002561    0.002920    0.012274   -0.001958    0.000988    0.001924   
std      1.002205    1.002656    0.987441    1.003227    1.003288    1.001916   
min     -1.128761   -3.421856   -3.673536   -1.499985   -4.519747   -1.138913   
50%     -0.022801    0.000098    0.038196    0.009843   -0.012183   -0.127722   
max      3.389896    2.609022    2.932473    3.127706    3.120557    3.282830   

             6           7           8           9     ...        6016  \
count  414.000000  414.000000  414.000000  414.000000  ...  414.000000   
mean    -0.001340    0.004880   -0.003373    0.002539  ...    0.005247   
std      1.003393    1.000715    1.002405    1.002617  ...    0.999735   
min     -3.945250   -2.750396   -4.870209   -3.236383  ...   -1.737364   
50%      0.035702    0.137816    0.035198    0.078814  ...   -0.054462   
max      3.551589    2.905629    3.907782    3.942526  ...    3.661318   

             6017        6018        6019        6020        6021        6022  \
count  414.000000  414.000000  414.000000  414.000000  414.000000  414.000000   
mean     0.000613    0.003743   -0.002270    0.000436   -0.003727    0.000030   
std      1.003579    1.001948    1.003043    1.003564    1.001374    1.003315   
min     -3.568733   -6.178395   -4.345745   -3.232178   -3.665220   -3.263316   
50%      0.028785    0.148808    0.010564    0.071302   -0.149710    0.068494   
max      3.128115    2.494707    2.613041    2.666078    3.523291    3.661753   

             6023        6024        6025  
count  414.000000  414.000000  414.000000  
mean    -0.002296    0.010420    0.000303  
std      1.002352    0.992282    1.003546  
min     -1.584669   -2.804049   -3.227633  
50%     -0.226664    0.080455   -0.109306  
max      3.360520    2.278268    2.748060  

[6 rows x 6026 columns]

# Résumé

In [119]:
columns = pd.MultiIndex.from_tuples(list(zip(["Résistance"]*5, Y.columns.tolist())) +
                                    list(zip(["Présence"]*3, ["gpa", "snps", "genexp"])))
df = pd.DataFrame([Y.isna().sum().tolist() + [X_gpa.isna().sum().sum()] + [X_snps.isna().sum().sum()] + [X_genexp.isna().sum().sum()],
                   Y_bincount.iloc[1, :].tolist() + [X_gpa_bincount[1]] + [X_snps_bincount[1]] + [None],
                   Y_bincount.iloc[0, :].tolist() + [X_gpa_bincount[0]] + [X_snps_bincount[0]] + [None]],
                  index=["# NA", "# VRAI", "# FAUX"],
                  columns=columns)
df

Résistance                                             Présence         \
       Tobramycin Ceftazidim Ciprofloxacin Meropenem Colistin      gpa   snps   
# NA            8         80            56        60        0        0      0   
# VRAI        130        165           199       244       85     3581   8218   
# FAUX        276        169           159       110      329    12424  64018   

               
       genexp  
# NA      0.0  
# VRAI    NaN  
# FAUX    NaN

In [120]:
df.to_latex(buf="rapport/tables/data.tex",
            float_format="%.0f",
            bold_rows=True,
            escape=True,
            caption="Résumé des variables réponses et des régresseurs.",
            label="tab:data",
            position="H")
with open("rapport/tables/data.tex", "r+") as f:
    text = f.read().replace("\\begin{tabular}", "\\resizebox{\\textwidth}{!}{\\begin{tabular}")
    text = text.replace("\\end{tabular}", "\\end{tabular}}")
    f.seek(0)
    f.write(text)
    f.close()

/tmp/ipykernel_42362/3806410242.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  df.to_latex(buf="rapport/tables/data.tex",
