In [1]:
import numpy as np

In [2]:
scores_cefta = np.load("results/cv/cv_scores__Ceftazidim.npy")
scores_cipro = np.load("results/cv/cv_scores__Ciprofloxacin.npy")
scores_colis = np.load("results/cv/cv_scores__Colistin.npy")
scores_merop = np.load("results/cv/cv_scores__Meropenem.npy")
scores_tobra = np.load("results/cv/cv_scores__Tobramycin.npy")

In [3]:
print((scores_cefta.mean(), scores_cefta.std()))
scores_cefta

(0.835204991087344, 0.09643411388737522)


array([0.68716578, 0.92557932, 0.80481283, 0.95543672, 0.8030303 ])

In [4]:
print((scores_cipro.mean(), scores_cipro.std()))
scores_cipro

(0.8832552729528537, 0.026991370384550267)


array([0.875     , 0.90625   , 0.8375    , 0.88341346, 0.9141129 ])

In [5]:
print((scores_colis.mean(), scores_colis.std()))
scores_colis

(0.7977444124502948, 0.11043539331196695)


array([0.59224599, 0.91087344, 0.81327986, 0.79901961, 0.87330317])

In [6]:
print((scores_merop.mean(), scores_merop.std()))
scores_merop

(0.8979243970315398, 0.041388333825377835)


array([0.88311688, 0.94434137, 0.82513915, 0.91372913, 0.92329545])

In [7]:
print((scores_tobra.mean(), scores_tobra.std()))
scores_tobra

(0.9509365634365634, 0.05007233906541514)


array([0.87706044, 0.98181818, 0.9048951 , 0.99090909, 1.        ])